name: Publish Image

on:
  push:
    branches:
      - master
      - staging
      - qa
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current branch
        uses: actions/checkout@v1
      - name: Set branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')" >> $GITHUB_ENV
      - name: Build Docker Image
        run: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && make publish BRANCH_NAME=${BRANCH_NAME}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
